sudo: required
services:
  - docker

before_install: 
    - docker build -t johnwesleyjb/docker-react -f Dockerfile.dev .

script: 
  - docker run johnwesleyjb/docker-react npm run test -- --coverage
